apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-api
  template:
    metadata:
      labels:
        app: mern-api
    spec:
      containers:
      - name: api
        image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000  
        - containerPort: 4000  
        envFrom:
        - secretRef:
            name: api-secrets
        env:
        - name: PORT
          value: "3000"
        - name: SOCKET_PORT
          value: "4000"

          

