apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-api
  template:
    metadata:
      labels:
        app: mern-api
    spec:
      containers:
      - name: api
        image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: api-secrets

