apiVersion: v1
kind: Service
metadata:
  name: mern-api-service
spec:
  selector:
    app: mern-api
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: websocket
      protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP  # Internal access only


---
apiVersion: v1
kind: Service
metadata:
  name: mern-client-service
spec:
  type: NodePort  # ✅ Changed to NodePort
  selector:
    app: mern-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # ✅ Exposes Client on NodePort 30082