apiVersion: v1
kind: Service
metadata:
  name: mern-api-service
spec:
  selector:
    app: mern-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mern-client-service
spec:
  selector:
    app: mern-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5176
  type: NodePort
