apiVersion: v1
kind: Service
metadata:
  name: mern-api-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use "nlb" for Network Load Balancer (recommended)
spec:
  selector:
    app: mern-api
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: websocket
      protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer  # Exposes the API to the internet

---
apiVersion: v1
kind: Service
metadata:
  name: mern-client-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: mern-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Exposes the Client (Frontend)
