apiVersion: v1
kind: Service
metadata:
  name: mern-api-service
spec:
  selector:
    app: mern-api
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: websocket
      protocol: TCP
      port: 4000
      targetPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: mern-client-service
spec:
  selector:
    app: mern-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
