apiVersion: v1
data:
  policy.csv: |
    p, admin, applications, *, get, allow
    p, admin, applications, *, create, allow
    p, admin, applications, *, update, allow
    p, admin, applications, *, delete, allow
    p, admin, applications, *, sync, allow
    p, admin, clusters, *, get, allow
    p, admin, clusters, *, create, allow
    p, admin, clusters, *, update, allow
    p, admin, clusters, *, delete, allow
    g, admin, role:admin
    g, admin, system:masters
  policy.default: role:readonly
  scopes: '[groups, email]'