apiVersion: v1
data:
  policy.csv: |
    p, admin, applications, *, get, allow
    p, admin, applications, *, create, allow
    p, admin, applications, *, update, allow
    p, admin, applications, *, delete, allow
    p, admin, applications, *, sync, allow
    p, admin, clusters, *, get, allow
    p, admin, clusters, *, create, allow
    p, admin, clusters, *, update, allow
    p, admin, clusters, *, delete, allow
    g, admin, role:admin
    g, admin, system:masters
  policy.default: role:readonly
  scopes: '[groups, email]'

kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  creationTimestamp: "2025-02-14T00:08:54Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "489188"
  uid: ff0fc6fb-34a8-438d-8244-e57dff62a0b0