api:
  image: omaremaddd/mern-api
  tag: latest
  port: 3000

client:
  image: omaremaddd/mern-client
  tag: latest
  port: 80

mongodb:
  image: mongo
  tag: latest
  port: 27017

serviceAccount:
  create: false  # Set to true if you want Helm to create a service account

autoscaling:
  enabled: false  # Set to true if you want auto-scaling
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

service:
  api:
    type: ClusterIP
    port: 3000
  client:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  apiHost: api.yalla.local    # Backend domain
  clientHost: yalla.local      # Frontend domain
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
  tls: false  # Change to true if using HTTPS


