api:
  image: 615299727797.dkr.ecr.me-south-1.amazonaws.com/yalla-n-travel
  tag: api-20250315154952
  pullPolicy: Always
  port: 3000
client:
  image: 615299727797.dkr.ecr.me-south-1.amazonaws.com/yalla-n-travel
  tag: client-20250315154952
  pullPolicy: Always
  port: 80
serviceAccount:
  create: false # Set to true if you want Helm to create a service account
autoscaling:
  enabled: false # Set to true if you want auto-scaling
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75
service:
  api:
    type: ClusterIP
    port: 3000
  client:
    type: NodePort
    port: 80
  type: ClusterIP # Explicitly define the type
ingress:
  enabled: false
