api:
  image: 615299727797.dkr.ecr.me-south-1.amazonaws.com/yalla-n-travel
  tag: mern-api-latest
  port: 3000

client:
  image: 615299727797.dkr.ecr.me-south-1.amazonaws.com/yalla-n-travel
  tag: mern-client-latest
  port: 80

mongodb:
  image: mongo
  tag: latest
  port: 27017

serviceAccount:
  create: false  # Set to true if you want Helm to create a service account

autoscaling:
  enabled: false  # Set to true if you want auto-scaling
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

service:
  api:
    type: LoadBalancer
    port: 3000
  client:
    type: LoadBalancer
    port: 80

ingress:
  enabled: true
  apiHost: api.yalla.local    # Backend domain
  clientHost: yalla.local      # Frontend domain
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=3600
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  tls: false  # Set to true if you plan to use HTTPS (with AWS ACM)


