version: "3.8"
services:
  backend:
    container_name: mern-api
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
