name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push API Image
      run: |
        docker build -t omaremaddd/mern-api:latest -f api/Dockerfile api/
        docker push omaremaddd/mern-api:latest

    - name: Build and Push Client Image
      run: |
        docker build -t omaremaddd/mern-client:latest -f client/Dockerfile client/
        docker push omaremaddd/mern-client:latest
