name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Kubernetes Config
      run: |
        echo "Creating Kubernetes config directory..."
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        cat $HOME/.kube/config  # Debugging: Check if the file exists
        chmod 600 $HOME/.kube/config  # Set correct permissions
        export KUBECONFIG=$HOME/.kube/config  # Ensure K8s CLI can find it
      shell: bash

    - name: Install Helm
      run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd-linux-amd64
        sudo mv argocd-linux-amd64 /usr/local/bin/argocd

    - name: Update Helm Image Tag
      run: |
        sed -i "s/tag: .*/tag: latest/" helm/values.yaml

    - name: Deploy with Helm
      run: |
        helm upgrade --install yalla-n-travel ./helm

    - name: Sync with ArgoCD
      run: |
        argocd app sync yalla-n-travel --grpc-web
