# name: Deploy to Kubernetes

# on:
#   workflow_run:
#     workflows: ["Build and Push Docker Images to AWS ECR"]
#     types:
#       - completed

# permissions:
#   id-token: write
#   contents: read
#   actions: read

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v4
#       with:
#         token: ${{ secrets.GH_PAT }}

#     - name: Retrieve Image Tag
#       run: echo "IMAGE_TAG=${{ needs.build.outputs.image_tag }}" >> $GITHUB_ENV

#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v2
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: me-south-1

#     - name: Set up Kubernetes Config for AWS EKS
#       run: aws eks update-kubeconfig --name yalla --region me-south-1

#     - name: Install Helm
#       run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

#     - name: Install ArgoCD CLI
#       run: |
#         curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
#         chmod +x argocd-linux-amd64
#         sudo mv argocd-linux-amd64 /usr/local/bin/argocd

#     - name: Install yq
#       run: |
#         sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
#         sudo chmod +x /usr/local/bin/yq

#     - name: Update Helm Image Tag
#       run: |
#         yq eval ".api.tag = \"api-$IMAGE_TAG\"" -i helm/values.yaml
#         yq eval ".client.tag = \"client-$IMAGE_TAG\"" -i helm/values.yaml

#     - name: Commit & Push Changes
#       env:
#         GH_PAT: ${{ secrets.GH_PAT }}
#       run: |
#         git config --global user.email "github-actions@github.com"
#         git config --global user.name "GitHub Actions"
#         git remote set-url origin https://${GH_PAT}@github.com/Omaremad2900/Yalla-N-Travel.git
#         git add helm/values.yaml
#         git commit -m "Update image tag to $IMAGE_TAG [skip ci]" || echo "No changes to commit"
#         git push origin main

#     - name: Force Kubernetes to Pull New Image
#       run: |
#         kubectl rollout restart deployment mern-api
#         kubectl rollout restart deployment mern-client
