name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Images to AWS ECR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Kubernetes Config
      run: |
        echo "Creating Kubernetes config directory..."
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        cat $HOME/.kube/config  # Debugging: Check if the file exists
        chmod 600 $HOME/.kube/config  # Set correct permissions
        export KUBECONFIG=$HOME/.kube/config  # Ensure K8s CLI can find it
      shell: bash

    - name: Install Helm
      run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd-linux-amd64
        sudo mv argocd-linux-amd64 /usr/local/bin/argocd

    - name: Update Helm Image Tag
      run: |
        sed -i "s/tag: .*/tag: latest/" helm/values.yaml

    - name: Load Image in minikube
      run: |
        minikube image load omaremaddd/mern-api:latest                           
        minikube image load omaremaddd/mern-client:latest


    - name: Deploy with Helm
      run: |
        helm upgrade --install yalla-n-travel ./helm

    - name: force restart
      run: |
        kubectl rollout restart deployment yalla-n-travel-api
        kubectl rollout restart deployment yalla-n-travel-client

    - name: Port Forward frontend service
      run: |
        kubectl port-forward svc/yalla-n-travel-client-service 8080:80

    - name: Sync with ArgoCD
      run: |
        argocd login --username admin --password Mx0hjjGa9lFvVtO8
        argocd app sync yalla-n-travel --grpc-web

    - name: Port forward ArgoCD
      run: |
        kubectl port-forward svc/argocd-server -n argocd 9090:443
